# Use the official MySQL image as the base image
FROM mysql:8.0.23

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=1234

# Create a database
ENV MYSQL_DATABASE=aline-db-container

# Optionally, set a MySQL user and password
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password123
