plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Owner: Trey-Crossley
keyed_groups:
  - key: tags.Application
    separator: ""
    prefix: ""
compose:
  ansible_host: public_dns_name
  ansible_user: ec2-user
  ansible_ssh_private_key_file: ../terraform/jenkins/jenkins_private_key.pem
  ansible_python_interpreter: /usr/bin/python3.9
  sonarqube_port: 9000

