apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/aline-financial-default: "true"
        io.kompose.service: gateway
    spec:
      containers:
        - image: 590184030834.dkr.ecr.us-east-1.amazonaws.com/gateway-tc:v3
          name: gateway
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: APP_PORT
            - name: APP_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: APP_SERVICE_HOST
            - name: PORTAL_LANDING
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: PORTAL_LANDING
            - name: PORTAL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: PORTAL_DASHBOARD
            - name: PORTAL_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: PORTAL_ADMIN

          ports:
            - containerPort: 8080
      restartPolicy: Always
