apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
data:
  APP_PORT: ODA4MA==  # Base64-encoded '8080'
  PORTAL_LANDING: aHR0cDovL2FhY2ZhMjE1M2RjYWQ0NGQ4ODIwN2I2MjQxZmE4MGYwLTExMzE0NDU5MzMudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29t  # Base64-encoded 'http://localhost:3000'
  PORTAL_DASHBOARD: aHR0cDovL2FhY2ZhMjE1M2RjYWQ0NGQ4ODIwN2I2MjQxZmE4MGYwLTExMzE0NDU5MzMudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tL21lbWJlcg==  # Base64-encoded 'http://localhost:4200'
  PORTAL_ADMIN: aHR0cDovL2FhY2ZhMjE1M2RjYWQ0NGQ4ODIwN2I2MjQxZmE4MGYwLTExMzE0NDU5MzMudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tL2FkbWlu  # Base64-encoded 'http://localhost:3007'
